### ISSUE TITLE
python verzió?

### ISSUE THREAD

**Issue by haa-zee** [bAndie91/gemlv#1]
Szia! Csak gondoltam, jelzem, hogy van egy kis anomália(?) a kódban: az egyetlen print parancs arra utal, hogy python2-re íródott a kód. Ha ez így van, akkor célszerű lenne az osztály az ajánlásnak (https://wiki.python.org/moin/NewClassVsClassicClass) megfelelően definiálni.

**Comment by bAndie91** [comment]
fixed in f5bec0e
